version: '3.1'

services:

  redis:
    image: redis
    ports:
    # for manual testing only, for productiion this can be removed
      - 0.0.0.0:6379:6379

  emit_time:
    image: codequants.com:5000/exchange-data:latest
    command: bash -c "source ~/.bashrc && python ./exchange_data/emitters/time_emitter.py"

  emit_bitmex:
    image: codequants.com:5000/exchange-data:latest
    command: bash -c "source ~/.bashrc && python ./exchange_data/emitters/emit-exchange-data --exchange bitmex XBTUSD"

  record_bitmex:
    image: codequants.com:5000/exchange-data:latest
    volumes:
      - $HOME/.exchange-data:/root/.exchange-data
    command: bash -c "source ~/.bashrc && python ./exchange_data/xarray_recorders/_bitmex.py XBTUSD"

#secrets:
#  postgres_password:
#    file: ./secrets/postgres_password
