version: '3.7'

networks:
  public:
    name: public
    external: true

services:

    model_host:
        deploy:
            replicas: 1
        image: tensorflow/serving:latest-gpu
        environment:
            - NVIDIA_VISIBLE_DEVCIES=all
        ports:
            - 0.0.0.0:8500:8500
            - 0.0.0.0:8501:8501
        volumes:
            - ${HOME}/.exchange-data/models/:/models
        networks:
            - public
        command: --model_config_file=/models/models.config --per_process_gpu_memory_fraction=0.05

secrets:
  DB:
      external: true

