version: '3.8'
networks:
    public:
        name: public
        external: true
services:

    orderbook:
        deploy:
            replicas: 1
            update_config:
                parallelism: 2
                delay: 20s
        image: 'registry.rubercubic.com:5001/exchange-data:latest'
        volumes:
            - '/var/run/docker.sock:/var/run/docker.sock'
        command: >-
            bash -c "source ~/.bashrc &&
            ./exchange_data/emitters/binance/orderbook_emitter.py -w 1 -F -m 300 --symbol-filter UNFIUSDT"
        secrets:
            - DB
            - ROLLBAR_API_KEY
        depends_on:
            - emit_time
            - redis
            - influxdb
        networks:
            - public

    orderbook_writer:
        deploy:
            replicas: 1
        image: 'registry.rubercubic.com:5001/exchange-data:latest'
        command: >-
            bash -c "source ~/.bashrc &&
            ./exchange_data/emitters/binance/orderbook_writer.py -F"
        secrets:
            - DB
            - ROLLBAR_API_KEY
        depends_on:
            - redis
            - influxdb
        networks:
            - public

    orderbook_writer_1m:
        deploy:
            replicas: 1
        image: 'registry.rubercubic.com:5001/exchange-data:latest'
        command: >-
            bash -c "source ~/.bashrc &&
            ./exchange_data/emitters/binance/orderbook_writer.py -F -s _1m"
        secrets:
            - DB
            - ROLLBAR_API_KEY
        depends_on:
            - redis
            - influxdb
        networks:
            - public

    ticker:
        deploy:
          # resources:
              #limits:
              #      cpus: '0.5'
            replicas: 1
        image: 'registry.rubercubic.com:5001/exchange-data:latest'
        volumes:
            - '/var/run/docker.sock:/var/run/docker.sock'
        command: >-
            bash -c "source ~/.bashrc &&
            ./exchange_data/emitters/binance/book_ticker_emitter.py -w 1 -F --symbol-filter UNFIUSDT"
        secrets:
            - DB
            - ROLLBAR_API_KEY
        depends_on:
            - redis
        networks:
            - public

    symbol:
        deploy:
          #resources:
          #      limits:
          #          cpus: '0.5'
            replicas: 1
            update_config:
                parallelism: 2
                delay: 20s
        image: 'registry.rubercubic.com:5001/exchange-data:latest'
        volumes:
            - '/var/run/docker.sock:/var/run/docker.sock'
        command: >-
            bash -c "source ~/.bashrc &&
            ./exchange_data/emitters/binance/symbol_emitter.py -w 1 -F --symbol-filter UNFIUSDT"
        environment:
            - LOG_LEVEL=INFO
        networks:
            - public
        depends_on:
            - redis

    trade:
        deploy:
            replicas: 1
            update_config:
                parallelism: 2
                delay: 20s
        image: 'registry.rubercubic.com:5001/exchange-data:latest'
        volumes:
            - '/var/run/docker.sock:/var/run/docker.sock'
        command: >-
            bash -c "source ~/.bashrc &&
            ./exchange_data/emitters/binance/trade_emitter.py -w 1 -F --symbol-filter UNFIUSDT"
        environment:
            - LOG_LEVEL=INFO
        networks:
            - public
        depends_on:
            - redis

    trade_writer:
        deploy:
            replicas: 1
        image: 'registry.rubercubic.com:5001/exchange-data:latest'
        command: >-
            bash -c "source ~/.bashrc &&
            ./exchange_data/emitters/binance/trade_writer.py -F -b 50"
        secrets:
            - DB
            - ROLLBAR_API_KEY
        depends_on:
            - redis
            - influxdb
        networks:
            - public
secrets:
    BITMEX_API_KEY:
        external: true
    BITMEX_API_SECRET:
        external: true
    DB:
        external: true
    ROLLBAR_API_KEY:
        external: true
