version: '3.7'

networks:
  public:
    name: public
    external: true

services:

  resnet_train:
    deploy:
      replicas: 0
    image: codequants.com:5000/exchange-data:latest
    command: bash -c "source ~/.bashrc && ./exchange_data/models/resnet/model.py --eval-span 3m -secs 180 -e 1"
    volumes:
      - "${HOME}/.exchange-data/:/root/.exchange-data/"
    environment:
        - NVIDIA_VISIBLE_DEVICES=all
    networks:
      - public

  resnet_server:
    deploy:
      replicas: 0
    image: tensorflow/serving
    volumes:
      - /home/joliveros/.exchange-data/models/resnet/:/models/resnet
    environment:
        - MODEL_NAME=resnet
        - NVIDIA_VISIBLE_DEVICES=all
    networks:
      - public
