version: '3.1'

services:

  redis:
    image: redis
#    ports:
#      - 0.0.0.0:6379:6379

  emit_bitmex:
    image: codequants.com:5000/exchange-data:latest
    command: bash -c "source ~/.bashrc && python ./exchange_data/emitters/emit-exchange-data --exchange bitmex XBTUSD"

  emit_time:
    image: codequants.com:5000/exchange-data:latest
    command: bash -c "source ~/.bashrc && python ./exchange_data/emitters/time_emitter.py"


#secrets:
#  postgres_password:
#    file: ./secrets/postgres_password
