FROM python:3.6-stretch

WORKDIR /src

COPY .bashrc /root

RUN apt-get update --fix-missing && \
    apt-get install -y \
    bzip2 \
    ca-certificates \
    curl \
    git\
    libsm6 \
    libxext6 \
    libxrender-dev \
    && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /src

COPY . .

RUN pip install --upgrade pip

RUN pip install -r requirements.txt
