version: 3

services:
  influxdb:
    image: influxdb
    restart: unless-stopped

    environment:
      - INFLUXDB_ADMIN_ENABLED=false
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_USER=save
      - INFLUXDB_USER_PASSWORD=jade121415

    ports:
    - 28953:8086

    volumes:
      - "${HOME}/scripts/influxdb.conf:/etc/influxdb/influxdb.conf"
      - "/mnt/volume-lon1-01/influxdb:/var/lib/influxdb"

    command:
    - -config /etc/influxdb/influxdb.conf

  bitmex-btcusd:
    env_file:
      - .env.prod
    links:
      - influxdb

