version: '3.7'
networks:
    public:
        name: public
        external: true
services:
    volatility_change_emitter:
        deploy:
            labels:
                - "swarm.cronjob.enable=true"
                - "swarm.cronjob.schedule=*/1 * * * *"
                - "swarm.cronjob.skip-running=false"
            replicas: 0
            restart_policy:
                condition: none
        image: 'registry.rubercubic.com:5001/exchange-data:latest'
        command: >-
            bash -c "source ~/.bashrc &&
            ./exchange_data/emitters/binance/volatility_change_emitter.py --tick"
        environment:
            - LOG_LEVEL=INFO
        networks:
            - public
        depends_on:
            - redis
            - influxdb

secrets:
    DB:
        external: true
