FROM tensorflow/tensorflow:2.4.0rc0-gpu

RUN apt-get update && apt-get install -y --no-install-recommends \
		git \
		vim \
		curl \
		wget \
		libgl1-mesa-glx \
	&& rm -rf /var/lib/apt/lists/*

WORKDIR /src

COPY . .

RUN pip install --upgrade pip

RUN pip install -r requirements.txt
