version: "3.8"

services:
  docker-stats:
    image: influxdb-docker-stats
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      - INFLUXDB_URL: /run/secrets/DB
    deploy:
      placement:
        constraints:
          - node.role == manager

secrets:
    DB:
        external: true

