version: '3.7'

services:

  redis:
    image: redis
    ports:
    # for manual testing only, for production this can be removed
      - 0.0.0.0:6379:6379

  emit_time:
    image: codequants.com:5000/exchange-data:latest
    command: bash -c "source ~/.bashrc && python ./exchange_data/emitters/time_emitter.py"
    depends_on:
      - redis

  emit_bitmex:
    deploy:
      replicas: 1
    image: codequants.com:5000/exchange-data:latest
    command: bash -c "source ~/.bashrc && python ./exchange_data/emitters/bitmex/_bitmex_websocket_emitter.py XBTUSD"
    depends_on:
      - redis

  emit_bitmex_orderbook:
    deploy:
      replicas: 1
    image: codequants.com:5000/exchange-data:latest
    command: bash -c "source ~/.bashrc && python ./exchange_data/emitters/bitmex/_bitmex_orderbook_emitter.py XBTUSD"
    volumes:
      - $HOME/.exchange-data:/root/.exchange-data
    env_file:
      - ./.env.prod
    depends_on:
      - emit_bitmex
      - emit_time
      - proxy

  socketio:
    image: codequants.com:5000/ws-server
    ports:
      - target: 8080
        mode: host
    environment:
#     - DEBUG=*
     - PORT=8080
    depends_on:
      - redis
    deploy:
      endpoint_mode: dnsrr
      replicas: 2
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
        max_attempts: 3
        window: 120s

  proxy:
    image: codequants.com:5000/ws-haproxy
    depends_on:
      - socketio
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./ws_service/haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    ports:
      - 0.0.0.0:8081:80
    environment:
      BACKENDS: "socketio"


#secrets:
#  postgres_password:
#    file: ./secrets/postgres_password
