version: '3.7'

networks:
  public:
    name: public
    external: true

services:

  emit_time:
    deploy:
      replicas: 1
    image: codequants.com:5000/exchange-data:latest
    command: bash -c "source ~/.bashrc && python ./exchange_data/emitters/time_emitter.py"
    networks:
      - public
    depends_on:
      - redis

  emit_bitmex_btc:
    deploy:
      replicas: 1
    image: codequants.com:5000/exchange-data:latest
    command: bash -c "source ~/.bashrc && python ./exchange_data/emitters/bitmex/_bitmex_websocket_emitter.py XBTUSD"
    networks:
      - public
    depends_on:
      - redis

  emit_bitmex_eth:
    deploy:
      replicas: 0
    image: codequants.com:5000/exchange-data:latest
    command: bash -c "source ~/.bashrc && python ./exchange_data/emitters/bitmex/_bitmex_websocket_emitter.py ETHUSD"
    networks:
      - public
    depends_on:
      - redis

  emit_orderbook_l2:
    deploy:
      replicas: 1
    image: codequants.com:5000/exchange-data:latest
    command: bash -c "source ~/.bashrc && python ./exchange_data/emitters/bitmex/_orderbook_l2_emitter.py XBTUSD"
    networks:
      - public
    depends_on:
      - redis

  emit_bxbt_index:
    deploy:
      replicas: 1
    image: codequants.com:5000/exchange-data:latest
    command: bash -c "source ~/.bashrc && python ./exchange_data/emitters/bitmex/_bxbt_index_emitter.py"
    environment:
      - LOG_LEVEL=INFO
    env_file:
      - ./.env.prod
    secrets:
        - BITMEX_API_KEY
        - BITMEX_API_SECRET
        - BITSTAMP_PUSHER_APP_KEY
        - DB
        - ROLLBAR_API_KEY
    networks:
      - public
    depends_on:
      - redis

  emit_bitmex_orderbook:
    deploy:
      replicas: 1
    image: codequants.com:5000/exchange-data:latest
    command: bash -c "source ~/.bashrc && python ./exchange_data/emitters/bitmex/_bitmex_orderbook_emitter.py XBTUSD"
    env_file:
      - ./.env.prod
    secrets:
      - BITMEX_API_KEY
      - BITMEX_API_SECRET
      - BITSTAMP_PUSHER_APP_KEY
      - DB
      - ROLLBAR_API_KEY
    depends_on:
      - emit_bitmex_btc
      - emit_time
      - redis
      - influxdb
    networks:
      - public

  record_bitmex_eth:
    deploy:
      replicas: 0
    image: codequants.com:5000/exchange-data:latest
    env_file:
      - ./.env.prod
    secrets:
      - BITMEX_API_KEY
      - BITMEX_API_SECRET
      - BITSTAMP_PUSHER_APP_KEY
      - DB
      - ROLLBAR_API_KEY
    depends_on:
      - influxdb
    command: bash -c "source ~/.bashrc && python ./exchange_data/recorders/_bitmex.py ETHUSD --measurement-name ETHUSD_ws"
    networks:
      - public

  record_bitmex_xbtusd:
    deploy:
      replicas: 1
    image: codequants.com:5000/exchange-data
    environment:
      - LOG_LEVEL=INFO
    env_file:
    - ./.env.prod
    secrets:
      - BITMEX_API_KEY
      - BITMEX_API_SECRET
      - BITSTAMP_PUSHER_APP_KEY
      - DB
      - ROLLBAR_API_KEY
    depends_on:
    - influxdb
    command: bash -c "source ~/.bashrc && python ./exchange_data/recorders/_bitmex.py XBTUSD --measurement-name data"
    networks:
    - public

  emit_bitmex_account:
    deploy:
      replicas: 1
    image: codequants.com:5000/exchange-data:latest
    command: bash -c "source ~/.bashrc && python ./exchange_data/emitters/bitmex/_account_emitter.py"
    environment:
      - LOG_LEVEL=INFO
    env_file:
      - ./.env.prod
    secrets:
      - BITMEX_API_KEY
      - BITMEX_API_SECRET
      - BITSTAMP_PUSHER_APP_KEY
      - DB
      - ROLLBAR_API_KEY
    networks:
      - public
    depends_on:
      - redis
      - influxdb

  emit_records_btc:
    deploy:
      replicas: 0
    image: codequants.com:5000/exchange-data:latest
    command: bash -c "source ~/.bashrc && python ./exchange_data/tfrecord/orderbook_tf_record.py -i 18m --frame-width 224 -c -s 16 -r 30s"
    volumes:
      - "${HOME}/.exchange-data/:/root/.exchange-data/"
    environment:
      - LOG_LEVEL=DEBUG
    env_file:
      - ./.env.prod
    networks:
      - public
    depends_on:
      - redis
      - influxdb
    secrets:
      - DB

secrets:
  BITMEX_API_KEY:
      external: true
  BITMEX_API_SECRET:
      external: true
  BITSTAMP_PUSHER_APP_KEY:
      external: true
  DB:
      external: true
  ROLLBAR_API_KEY:
      external: true
