version: '3.7'

networks:
  public:
    name: public
    external: true

services:

  resnet_train:
    deploy:
      replicas: 1
    image: codequants.com:5000/exchange-data:latest
    command: bash -c "source ~/.bashrc && ./exchange_data/models/resnet/model.py --eval-span 30m -e 15 --frame-width 224 -i 6h -w 3s --steps-epoch 6m --eval-steps 30s -l 0.0000001 --learning-rate-decay 0.00001"
    volumes:
      - "${HOME}/.exchange-data/:/root/.exchange-data/"
    environment:
        - NVIDIA_VISIBLE_DEVICES=all
    depends_on:
      - influxdb
      - redis
    networks:
      - public
    secrets:
      - DB

  resnet_server:
    deploy:
      replicas: 1
    image: tensorflow/serving
    ports:
      - 0.0.0.0:8500:8500
      - 0.0.0.0:8501:8501
    volumes:
      - /home/joliveros/.exchange-data/models/resnet/saved:/models/resnet
    environment:
        - MODEL_NAME=resnet
        - NVIDIA_VISIBLE_DEVICES=all
    networks:
      - public

  virtual_executor:
    deploy:
        replicas: 1
    image: codequants.com:5000/exchange-data:latest
    command: bash -c "source ~/.bashrc && ./exchange_data/trading/virtual_trade_executor.py XBTUSD -l 10.0 -c 0.0034482758620689655"
    environment:
        - NVIDIA_VISIBLE_DEVICES=all
    depends_on:
        - redis
    networks:
        - public
    secrets:
        - DB

secrets:
  DB:
      external: true

