version: '3.8'
networks:
    public:
        name: public
        external: true
services:
    symbol_emitter:
        deploy:
          replicas: 1
          update_config:
            parallelism: 2
            delay: 20s
        image: 'registry.rubercubic.com:5001/exchange-data:latest'
        command: >-
            bash -c "source ~/.bashrc &&
            ./exchange_data/emitters/binance/symbol_emitter.py"
        environment:
            - LOG_LEVEL=INFO
        networks:
            - public
        depends_on:
            - redis

    emit_and_record_depths:
        deploy:
            replicas: 0
            #placement:
              #constraints: [node.hostname == ip-172-31-19-30]
        image: 'registry.rubercubic.com:5001/exchange-data:latest'
        command: >-
            bash -c "source ~/.bashrc &&
            ./exchange_data/emitters/binance/emit_and_record_depths.py"
        env_file:
            - ./.env.prod
        secrets:
            - DB
            - ROLLBAR_API_KEY
        depends_on:
            - emit_time
            - redis
            - influxdb
        networks:
            - public

secrets:
    BITMEX_API_KEY:
        external: true
    BITMEX_API_SECRET:
        external: true
    DB:
        external: true
    ROLLBAR_API_KEY:
        external: true

