version: '3.8'

networks:
  public:
    name: public
    external: true

services:
    model_serving:
        deploy:
            replicas: 1
        image: tensorflow/serving:latest-gpu
        environment:
            - NVIDIA_VISIBLE_DEVICES=all
        ports:
            - "0.0.0.0:8500:8500"
            - "0.0.0.0:8501:8501"
        volumes:
            - ${HOME}/.exchange-data:/root/.exchange-data
        networks:
            - public
        command: --model_config_file=/root/.exchange-data/models/models.config --per_process_gpu_memory_fraction=0.12 --model_config_file_poll_wait_seconds=30

    FTT:
        deploy:
            replicas: 2
        image: 'registry.rubercubic.com:5001/exchange-data:latest'
        volumes:
            - ${HOME}/.exchange-data/:/home/joliveros/.exchange-data/
        command: >-
            bash -c "source ~/.bashrc &&
            ./exchange_data/models/resnet/tune.py FTTBNB -i 13h -b 13h -o 6h -w 3m -g 1m --group-by-min 2 -m 148 -D 6 --min-capital 1.005 -e -c 72"
        environment:
            - LOG_LEVEL=INFO
            - NVIDIA_VISIBLE_DEVICES=all
        networks:
            - public
        depends_on:
            - influxdb
            - model_serving
            - redis
        secrets:
            - DB

    MFT:
        deploy:
            replicas: 2
        image: 'registry.rubercubic.com:5001/exchange-data:latest'
        volumes:
            - ${HOME}/.exchange-data/:/home/joliveros/.exchange-data/
        command: >-
            bash -c "source ~/.bashrc &&
            ./exchange_data/models/resnet/tune.py MFTBNB -i 13h -b 13h -o 6h -w 3m -g 1m --group-by-min 2 -m 148 -D 6 --min-capital 1.005 -e -c 72"
        environment:
            - LOG_LEVEL=INFO
            - NVIDIA_VISIBLE_DEVICES=all
        networks:
            - public
        depends_on:
            - influxdb
            - model_serving
            - redis
        secrets:
            - DB
secrets:
  DB:
      external: true

