version: '3.1'

services:

  redis:
    image: redis
    ports:
    # for manual testing only, for production this can be removed
      - 0.0.0.0:6379:6379

  emit_time:
    image: codequants.com:5000/exchange-data:latest
    command: bash -c "source ~/.bashrc && python ./exchange_data/emitters/time_emitter.py"
    depends_on:
      - redis

  emit_bitmex:
    deploy:
      replicas: 1
    image: codequants.com:5000/exchange-data:latest
    command: bash -c "source ~/.bashrc && python ./exchange_data/emitters/bitmex/_bitmex_websocket_emitter.py XBTUSD"
    depends_on:
      - redis

  emit_bitmex_orderbook:
    deploy:
      replicas: 0
    image: codequants.com:5000/exchange-data:latest
    command: bash -c "source ~/.bashrc && python ./exchange_data/emitters/bitmex/_bitmex_orderbook_emitter.py XBTUSD"
    volumes:
      - $HOME/.exchange-data:/root/.exchange-data
    env_file:
      - ./.env.prod
    depends_on:
      - emit_bitmex
      - emit_time

  socketio:
    image: codequants.com:5000/ws_server
    ports:
     - 8080
    environment:
     - SERVICE_PORTS=8080
     - PORT=8080
    deploy:
     replicas: 2
     update_config:
       parallelism: 2
       delay: 10s
     restart_policy:
       condition: on-failure
       max_attempts: 3
       window: 120s
    depends_on:
      - redis

  proxy:
    image: dockercloud/haproxy
    depends_on:
      - socketio
    environment:
      - BALANCE=leastconn
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 0.0.0.0:8081:80

#secrets:
#  postgres_password:
#    file: ./secrets/postgres_password
