version: '3.8'

networks:
  public:
    name: public
    external: true

services:
    model_serving:
        deploy:
           replicas: 1
        image: tensorflow/serving:latest-gpu
        environment:
            - NVIDIA_VISIBLE_DEVICES=all
        ports:
            - "0.0.0.0:8500:8500"
            - "0.0.0.0:8501:8501"
        volumes:
            - ${HOME}/.exchange-data:/root/.exchange-data
        networks:
            - public
        command: --model_config_file=/root/.exchange-data/models/models.config --per_process_gpu_memory_fraction=0.25 --model_config_file_poll_wait_seconds=30

    WAVESUSDT:
        deploy:
            replicas: 3
        image: 'registry.rubercubic.com:5001/exchange-data:latest'
        volumes:
            - ${HOME}/.exchange-data/:/home/joliveros/.exchange-data/
        command: >-
            bash -c "source ~/.bashrc &&
            ./exchange_data/models/resnet/tune.py WAVESUSDT -i 2h -b 2h -o 30m -w 20s -g 5s --group-by-min 10s -m 172 -D 5 --min-capital 1.005 -e -d 92 -l 44 --database-name binance_futures"
        environment:
            - LOG_LEVEL=INFO
            - NVIDIA_VISIBLE_DEVICES=all
        networks:
            - public
        depends_on:
            - influxdb
            - model_serving
            - redis
        secrets:
            - DB
secrets:
  DB:
      external: true

