version: '3.1'

services:

  redis:
    image: redis
    ports:
    # for manual testing only, for productiion this can be removed
      - 0.0.0.0:6379:6379

  emit_time:
    image: codequants.com:5000/exchange-data:latest
    command: bash -c "source ~/.bashrc && python ./exchange_data/emitters/time_emitter.py"
    depends_on:
      - redis

  emit_bitmex:
    image: codequants.com:5000/exchange-data:latest
    command: bash -c "source ~/.bashrc && python ./exchange_data/emitters/emit-exchange-data --exchange bitmex XBTUSD"
    depends_on:
      - redis
  record_bitmex:
    deploy:
      replicas: 0
    image: codequants.com:5000/exchange-data:latest
    volumes:
      - $HOME/.exchange-data:/root/.exchange-data
    command: bash -c "source ~/.bashrc && python ./exchange_data/xarray_recorders/_xarray_recorder.py XBTUSD"
    depends_on:
      - redis
  emit_bitmex_orderbook:
    deploy:
      replicas: 1
    image: codequants.com:5000/exchange-data:latest
    command: bash -c "source ~/.bashrc && python ./exchange_data/emitters/bitmex/_bitmex_orderbook_emitter.py XBTUSD --save-interval 1m"
    volumes:
      - $HOME/.exchange-data:/root/.exchange-data
    env_file:
      - ./.env.prod
    depends_on:
      - redis

  ws_server:
    deploy:
      replicas: 0
    image: codequants.com:5000/exchange-data-ws:latest
    env_file:
      - ./.env.prod

#secrets:
#  postgres_password:
#    file: ./secrets/postgres_password
