version: '3.1'

services:

  redis:
    image: redis

  emit_bitmex:
    image: codequants/exchange-data
    command: ./emit-exchange-data --exchange bitmex XBTUSD
    volumes:
      - ./:/src/

  emit_time:
    image: codequants/exchange-data
    command: ./emit-time
    volumes:
      - ./:/src/

#  bitmex_data:
#    image: codequants/exchange-data
#    command: ./exchange-data --exchange bitmex XBTUSD


#secrets:
#  postgres_password:
#    file: ./secrets/postgres_password
