version: '3.7'
networks:
    public:
        name: public
        external: true
services:
    emit_depth:
        deploy:
            replicas: 1
        image: 'registry.rubercubic.com:5001/exchange-data:latest'
        command: >-
            bash -c "source ~/.bashrc &&
            ./exchange_data/emitters/binance/_depth_emitter.py $SYMBOL"
        environment:
            - LOG_LEVEL=INFO
        networks:
            - public
        depends_on:
            - redis

    emit_and_record_depths:
        deploy:
            replicas: 1
        image: 'registry.rubercubic.com:5001/exchange-data:latest'
        command: >-
            bash -c "source ~/.bashrc &&
            ./exchange_data/emitters/binance/_binance_orderbook_emitter.py $SYMBOL"
        env_file:
            - ./.env.prod
        secrets:
            - DB
            - ROLLBAR_API_KEY
        depends_on:
            - emit_time
            - redis
        networks:
            - public

#    emit_bitmex_account:
#        deploy:
#            replicas: 1
#        image: 'registry.rubercubic.com:5001/exchange-data'
#        command: >-
#            bash -c "source ~/.bashrc &&
#            ./exchange_data/emitters/bitmex/_account_emitter.py"
#        environment:
#            - LOG_LEVEL=INFO
#        env_file:
#            - ./.env.prod
#        secrets:
#            - BITMEX_API_KEY
#            - BITMEX_API_SECRET
#            - DB
#            - ROLLBAR_API_KEY
#        networks:
#            - public
#        depends_on:
#            - redis
#            - influxdb
#

    emit_trading_window:
        deploy:
            replicas: 0
        image: 'registry.rubercubic.com:5001/exchange-data:latest'
        command: >-
            bash -c "source ~/.bashrc &&
            ./exchange_data/emitters/trading_window_emitter.py -i 3h -s $SYMBOL"
        environment:
            - LOG_LEVEL=INFO
        env_file:
            - ./.env.prod
        networks:
            - public
        depends_on:
            - redis
            - influxdb
        secrets:
            - DB

    emit_prediction_btc:
        deploy:
            replicas: 0
        image: 'registry.rubercubic.com:5001/exchange-data:latest'
        command: >-
            bash -c "source ~/.bashrc &&
            ./exchange_data/emitters/prediction_emitter.py $SYMBOL -v 1e4"
        environment:
            - LOG_LEVEL=INFO
        env_file:
            - ./.env.prod
        networks:
            - public
        depends_on:
            - resnet_server
            - redis
            - influxdb
        secrets:
            - DB

#    virtual_executor:
#        deploy:
#            replicas: 1
#        image: 'registry.rubercubic.com:5001/exchange-data:latest'
#        command: >-
#            bash -c "source ~/.bashrc &&
#            ./exchange_data/trading/virtual_trade_executor.py XBTUSD -l 1.0 -c 1.0"
#        environment:
#            - CUDA_VISIBLE_DEVICES=-1
#        depends_on:
#            - redis
#        networks:
#            - public
#        secrets:
#            - DB
#
#    trade_executor:
#        deploy:
#            replicas: 0
#        image: 'registry.rubercubic.com:5001/exchange-data:latest'
#        command: >-
#            bash -c "source ~/.bashrc &&
#            ./exchange_data/trading/_trade_executor.py XBTUSD -p 0 -l 1"
#        environment:
#            - CUDA_VISIBLE_DEVICES=-1
#        depends_on:
#            - redis
#            - influxdb
#        networks:
#            - public
#        secrets:
#            - BITMEX_API_KEY
#            - BITMEX_API_SECRET
#            - DB
#
    resnet_server:
        deploy:
            replicas: 0
        image: tensorflow/serving:2.1.0
        ports:
#            - 0.0.0.0:8500:8500
#            - 0.0.0.0:8501:8501
        volumes:
            - /home/joliveros/.exchange-data/models/${SYMBOL}_export:/models/resnet
        environment:
            - CUDA_VISIBLE_DEVICES=-1
            - MODEL_NAME=resnet
        networks:
            - public

secrets:
    BITMEX_API_KEY:
        external: true
    BITMEX_API_SECRET:
        external: true
    DB:
        external: true
    ROLLBAR_API_KEY:
        external: true

