version: '3.7'

networks:
  public:
    name: public
    external: true

services:

    server:
        deploy:
            replicas: 1
        image: tensorflow/serving
        ports:
            - 0.0.0.0:8500:8500
            - 0.0.0.0:8501:8501
        volumes:
            - ${HOME}/.exchange-data/models/:/models
            - ./tfserving/models.config:/models/models.config
        environment:
            - CUDA_VISIBLE_DEVICES=-1
        networks:
            - public
        command: --model_config_file=/models/models.config

secrets:
  DB:
      external: true

