version: '3.8'

networks:
  public:
    name: public
    external: true

services:
    model_serving:
        deploy:
            replicas: 1
        image: tensorflow/serving:latest-gpu
        environment:
            - NVIDIA_VISIBLE_DEVICES=all
        ports:
            - 0.0.0.0:8500:8500
            - 0.0.0.0:8501:8501
        volumes:
            - ${HOME}/.exchange-data/models/:/models
            - ${HOME}/.exchange-data/best_exported_models/:/best_exported_models
        networks:
            - public
        command: --model_config_file=/models/models.config --per_process_gpu_memory_fraction=0.03

    BNB:
        deploy:
            replicas: 3
        image: 'registry.rubercubic.com:5001/exchange-data:latest'
        volumes:
            - ${HOME}/.exchange-data/:/home/joliveros/.exchange-data/
        command: >-
            bash -c "source ~/.bashrc &&
            ./exchange_data/models/resnet/tune.py ZENBNB -i 7d -b 7d -o 0h -w 3m -g 2m -n 3 -m 172 -D 4 --min-capital 1.12 -c 40"
        environment:
            - LOG_LEVEL=INFO
            - NVIDIA_VISIBLE_DEVICES=all
        networks:
            - public
        depends_on:
            - influxdb
            - model_host
            - redis
        secrets:
            - DB

secrets:
  DB:
      external: true

