version: '3.8'
networks:
    public:
        name: public
        external: true
services:
    emitter:
        deploy:
            resources:
                limits:
                    cpus: '0.4'
            replicas: 3
            update_config:
                parallelism: 2
                delay: 20s
        image: 'registry.rubercubic.com:5001/exchange-data:latest'
        volumes:
            - '/var/run/docker.sock:/var/run/docker.sock'
        command: >-
            bash -c "source ~/.bashrc &&
            ./exchange_data/emitters/binance/symbol_emitter.py -w 3"
        environment:
            - LOG_LEVEL=INFO
        networks:
            - public
        depends_on:
            - redis

secrets:
    BITMEX_API_KEY:
        external: true
    BITMEX_API_SECRET:
        external: true
    DB:
        external: true
    ROLLBAR_API_KEY:
        external: true
