version: '3.8'
networks:
    public:
        name: public
        external: true
services:

    emitter:
        deploy:
            replicas: 6
            update_config:
                parallelism: 2
                delay: 20s
        image: 'registry.rubercubic.com:5001/exchange-data:latest'
        volumes:
            - '/var/run/docker.sock:/var/run/docker.sock'
        command: >-
            bash -c "source ~/.bashrc &&
            ./exchange_data/emitters/binance/orderbook_emitter.py -w 6"
        secrets:
            - DB
            - ROLLBAR_API_KEY
        depends_on:
            - emit_time
            - redis
            - influxdb
        networks:
            - public

secrets:
    BITMEX_API_KEY:
        external: true
    BITMEX_API_SECRET:
        external: true
    DB:
        external: true
    ROLLBAR_API_KEY:
        external: true
