version: "3.8"

networks:
    public:
        name: public
        external: true

services:
  docker-stats:
    image: liveify/influxdb-docker-stats
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      - INFLUXDB_URL="${DB}"
    deploy:
      placement:
        constraints:
          - node.role == manager
    networks:
        - public

