version: '3.8'

networks:
  public:
    name: public
    external: true

services:

    model_host:
        deploy:
            replicas: 1
        image: tensorflow/serving:latest-gpu
        environment:
            - NVIDIA_VISIBLE_DEVCIES=all
        ports:
            - 0.0.0.0:8500:8500
            - 0.0.0.0:8501:8501
        volumes:
            - ${HOME}/.exchange-data/models/:/models
        networks:
            - public
        command: --model_config_file=/models/models.config --per_process_gpu_memory_fraction=0.03

    RUNE:
        deploy:
            replicas: 4
        image: 'registry.rubercubic.com:5001/exchange-data:latest'
        volumes:
            - ${HOME}/.exchange-data/:/root/.exchange-data
        command: >-
            bash -c "source ~/.bashrc &&
            ./exchange_data/models/resnet/tune.py RUNEBNB -i 14d -b 14d -o 1d -w 3m -g 1m -s 4 -n 4 -m 250 -D 4"
        environment:
            - LOG_LEVEL=INFO
            - NVIDIA_VISIBLE_DEVCIES=all
        networks:
            - public
        depends_on:
            - influxdb
            - model_host
            - redis
        secrets:
            - DB

secrets:
  DB:
      external: true

