name: exchange-data
channels:
  - defaults
  - anaconda
dependencies:
  - boost
  - bottleneck
  - cython
  - matplotlib
  - netcdf4
  - pip==19.3.1
  - python=3.6.5
  - toolz
  - xarray
  - scikit-image
  - pip:
    - alog
    - bitmex
    - bitmex-websocket
    - cached-property
    - click
    - coveralls
    - dill
    - flake8
    - git+https://github.com/joliveros/gdax-python.git#egg=gdax
    - git+https://github.com/joliveros/sec.git#egg=sec
    - git+https://github.com/nlsdfnbch/Pysher.git#egg=pysher
    - gym
    - influxdb
    - joblib
    - mock
    - opencv-python
    - optuna
    - pandas==0.25.3
    - progressbar2
    - prometheus_client
    - pusherclient
    - pytest
    - pytest-cov
    - pytest-mock
    - pytest-mypy
    - pytest-vcr
    - python-socketio[client]
    - pytimeparse
    - redis
    - rollbar>=0.13.12
    - sortedcontainers
    - statsd
    - stringcase
    - tf-nightly-gpu
    - mplfinance
    - timestamp
    - tqdm
