name: exchange-data
channels:
  - defaults
  - anaconda
dependencies:
  - boost
  - bottleneck
  - cython
  - netcdf4
  - numpy
  - pip=10.0.1
  - python=3.6.5
  - toolz
  - xarray
  - matplotlib
  - pip:
    - pytest-mypy
    - ray[rllib,debug,dashboard]
    - alog
    - bitmex
    - bitmex-websocket
    - cached-property
    - click
    - coveralls
    - flake8
    - git+https://github.com/joliveros/gdax-python.git#egg=gdax
    - git+https://github.com/nlsdfnbch/Pysher.git#egg=pysher
    - gym
    - influxdb
    - mock
    - pusherclient
    - pytest
    - pytest-cov
    - pytest-mock
    - pytest-vcr
    - python-socketio[client]
    - pytimeparse
    - redis
    - rollbar>=0.13.12
    - sortedcontainers
    - statsd
    - stringcase
    - timestamp
