version: "3.1"

services:
  influxdb:
    image: influxdb
    restart: unless-stopped

    env_file:
      - ./.env.prod

    ports:
    - 28953:8086

    volumes:
      - "./influxdb.conf:/etc/influxdb/influxdb.conf"
      - "${HOME}/influxdb:/var/lib/influxdb"

    command: influxd -config /etc/influxdb/influxdb.conf

  bitmex-btcusd:
    image: codequants/exchange-data

    env_file:
      - ./.env.prod

    environment:
      - BATCH_SIZE=100

    depends_on:
      - influxdb

    command: bash -c "source ~/.bashrc && ./exchange-data --exchange bitmex XBTUSD"

  bitstamp-btcusd:
    image: codequants/exchange-data
    restart: unless-stopped

    env_file:
      - ./.env.prod

    environment:
      - BATCH_SIZE=100

    depends_on:
      - influxdb

    command: bash -c "source ~/.bashrc && ./exchange-data --exchange bitstamp btcusd"

  gdax-btcusd:
    image: codequants/exchange-data
    restart: unless-stopped

    env_file:
      - ./.env.prod

    environment:
      - BATCH_SIZE=100

    depends_on:
      - influxdb

    command: bash -c "source ~/.bashrc && ./exchange-data --exchange gdax BTC-USD"
