version: "3.7"

networks:
  public:
    name: public
    external: true

services:
    redis:
        image:
            redis
        ports:
            - 0.0.0.0:6379:6379
        networks:
            - public

    influxdb:
        image: influxdb
        env_file:
            - ./.env.prod
        ports:
            - 0.0.0.0:28953:8086
        volumes:
            - "./influxdb.conf:/etc/influxdb/influxdb.conf"
            - "${HOME}/influxdb:/var/lib/influxdb"

        command: influxd -config /etc/influxdb/influxdb.conf
        networks:
            - public
