version: "3.7"

networks:
  public:
    name: public
    external: true

services:
    redis:
        image:
            redis
        ports:
            - 0.0.0.0:6379:6379
        networks:
            - public

    influxdb:
        deploy:
          resources:
              limits:
                  memory: 4G
        image: influxdb
        env_file:
            - ./.env.prod
        ports:
            - 0.0.0.0:28953:8086
        volumes:
            - "./influxdb.conf:/etc/influxdb/influxdb.conf"
            - "${HOME}/influxdb:/var/lib/influxdb"

        command: influxd -config /etc/influxdb/influxdb.conf
        networks:
            - public

    bitmex-xbtusd:
      image: codequants.com:5000/exchange-data
      env_file:
        - ./.env.prod
      depends_on:
        - influxdb
      command: bash -c "source ~/.bashrc && python ./exchange_data/recorders/_bitmex.py XBTUSD"
      networks:
        - public

    bitstamp-btcusd:
      image: codequants.com:5000/exchange-data
      env_file:
        - ./.env.prod
      environment:
        - BATCH_SIZE=100

      depends_on:
        - influxdb

      command: bash -c "source ~/.bashrc && ./exchange-data --exchange bitstamp btcusd"
      networks:
        - public

    gdax-btcusd:
      image: codequants.com:5000/exchange-data
      env_file:
        - ./.env.prod
      environment:
        - BATCH_SIZE=100

      depends_on:
        - influxdb

      command: bash -c "source ~/.bashrc && ./exchange-data --exchange gdax BTC-USD"
      networks:
          - public

