version: "3.7"

networks:
  public:
    name: public
    external: true

services:
    redis:
        image:
            redis
        volumes:
            - "./redis.conf:/usr/local/etc/redis/redis.conf"
        environment:
            - "constraint:node==ip-172-31-38-16"
        ports:
            - 0.0.0.0:6379:6379
        networks:
            - public
        command: redis-server /usr/local/etc/redis/redis.conf

    influxdb:
        deploy:
          resources:
            limits:
              memory: 6144M
        image: registry.rubercubic.com:5001/influxdb
        env_file:
          - ./.env.prod
        environment:
          - "constraint:node==ip-172-31-38-16"
        secrets:
            - INFLUXDB_ADMIN_PASSWORD
        ports:
            - 0.0.0.0:28736:8086
        volumes:
            - "/home/$USER/influxdb:/var/lib/influxdb"

        command: influxd -config /etc/influxdb/influxdb.conf
        networks:
            - public

    emit_time:
        deploy:
            replicas: 1
        image: 'registry.rubercubic.com:5001/exchange-data:latest'
        command: bash -c "source ~/.bashrc && ./exchange_data/emitters/time_emitter.py"
        networks:
            - public
        depends_on:
            - redis
            - influxdb

secrets:
    INFLUXDB_ADMIN_PASSWORD:
        external: true
