version: "3.7"

networks:
  public:
    name: public
    external: true

services:
    redis:
        image:
            redis
        ports:
            - 0.0.0.0:6379:6379
        networks:
            - public

    influxdb:
        image: codequants.com:5000/influxdb
        env_file:
          - ./.env.prod
        secrets:
            - INFLUXDB_ADMIN_PASSWORD
        ports:
            - 0.0.0.0:28736:8086
        volumes:
            - "/home/joliveros/exchange-data/influxdb.conf:/etc/influxdb/influxdb.conf"
            - "/home/joliveros/influxdb:/var/lib/influxdb"

        command: influxd -config /etc/influxdb/influxdb.conf
        networks:
            - public

secrets:
    INFLUXDB_ADMIN_PASSWORD:
        external: true
