version: "3.7"

networks:
  public:
    name: public
    external: true

services:
    redis:
        image:
            redis
        volumes:
            - "./redis.conf:/usr/local/etc/redis/redis.conf"
        ports:
            - 0.0.0.0:6379:6379
        networks:
            - public
        command: redis-server /usr/local/etc/redis/redis.conf

    influxdb:
        image: registry.rubercubic.com:5001/influxdb
        env_file:
          - ./.env.prod
        secrets:
            - INFLUXDB_ADMIN_PASSWORD
        ports:
            - 0.0.0.0:28736:8086
        volumes:
            - "/home/$USER/influxdb:/var/lib/influxdb"

        command: influxd -config /etc/influxdb/influxdb.conf
        networks:
            - public

secrets:
    INFLUXDB_ADMIN_PASSWORD:
        external: true
