version: "3.7"

services:
  swarm-cronjob:
    image: crazymax/swarm-cronjob
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      - "LOG_LEVEL=debug"
      - "LOG_JSON=false"
    deploy:
      placement:
        constraints:
          - node.role == manager
