version: '3.7'

networks:
  public:
    name: public
    external: true

services:

  emit_time:
    deploy:
      replicas: 1
    image: codequants.com:5000/exchange-data:latest
    command: bash -c "source ~/.bashrc && python ./exchange_data/emitters/time_emitter.py"
    networks:
      - public
    depends_on:
      - redis

  emit_bitmex_btc:
    deploy:
      replicas: 1
    image: codequants.com:5000/exchange-data:latest
    command: bash -c "source ~/.bashrc && python ./exchange_data/emitters/bitmex/instrument_emitter.py XBTUSD"
    networks:
      - public
    depends_on:
      - redis

  emit_bitmex_eth:
    deploy:
      replicas: 0
    image: codequants.com:5000/exchange-data:latest
    command: bash -c "source ~/.bashrc && python ./exchange_data/emitters/bitmex/instrument_emitter.py ETHUSD"
    networks:
      - public
    depends_on:
      - redis

  emit_orderbook_l2:
    deploy:
      replicas: 0
    image: codequants.com:5000/exchange-data:latest
    command: bash -c "source ~/.bashrc && python ./exchange_data/emitters/bitmex/_orderbook_l2_emitter.py XBTUSD"
    networks:
      - public
    depends_on:
      - redis

  emit_bxbt_index:
    deploy:
      replicas: 0
    image: codequants.com:5000/exchange-data:latest
    command: bash -c "source ~/.bashrc && python ./exchange_data/emitters/bitmex/_bxbt_index_emitter.py"
    env_file:
      - ./.env.prod
    networks:
      - public
    depends_on:
      - redis

  emit_bitmex_orderbook:
    deploy:
      replicas: 0
    image: codequants.com:5000/exchange-data:latest
    command: bash -c "source ~/.bashrc && python ./exchange_data/emitters/bitmex/_bitmex_orderbook_emitter.py XBTUSD"
    volumes:
      - $HOME/.exchange-data:/root/.exchange-data
    env_file:
      - ./.env.prod
    depends_on:
      - emit_bitmex_btc
      - emit_time
      - redis
      - influxdb
#      - proxy
    networks:
      - public

  record_bitmex_eth:
    deploy:
      replicas: 0
    image: codequants.com:5000/exchange-data
    env_file:
      - ./.env.prod
    depends_on:
      - influxdb
    command: bash -c "source ~/.bashrc && python ./exchange_data/recorders/_bitmex.py ETHUSD --measurement-name ETHUSD_ws"
    networks:
      - public

  record_bitmex_xbtusd:
    deploy:
      replicas: 0
    image: codequants.com:5000/exchange-data
    env_file:
    - ./.env.prod
    depends_on:
    - influxdb
    command: bash -c "source ~/.bashrc && python ./exchange_data/recorders/_bitmex.py XBTUSD --measurement-name data"
    networks:
    - public

  emit_bitmex_account:
    deploy:
      replicas: 0
    image: codequants.com:5000/exchange-data:latest
    command: bash -c "source ~/.bashrc && python ./exchange_data/emitters/bitmex/_account_emitter.py"
    env_file:
      - ./.env.prod
    networks:
      - public
    depends_on:
      - redis
      - influxdb

  socketio:
    image: codequants.com:5000/ws-server
    ports:
      - target: 8083
        mode: host
    environment:
#     - DEBUG=*
     - PORT=8083
#    volumes:
#      - ./ws_service/server/index.js:/usr/src/app/index.js
    depends_on:
      - redis
    deploy:
      endpoint_mode: dnsrr
      replicas: 0
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
        max_attempts: 3
        window: 120s
    networks:
      - public

  proxy:
    deploy:
      replicas: 0
    image: codequants.com:5000/ws-haproxy
    depends_on:
      - socketio
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./ws_service/haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    ports:
      - 0.0.0.0:8081:80
    environment:
      BACKENDS: "socketio"
    networks:
      - public


secrets:
  BITMEX_API_KEY:
      external: true
  BITMEX_API_SECRET:
      external: true
  BITSTAMP_PUSHER_APP_KEY:
      external: true
  DB:
      external: true
  ROLLBAR_API_KEY:
      external: true
