#! /usr/bin/env python
from stringcase import pascalcase

import click
import exchange_data.emitters.__init__
import signal

signal.signal(signal.SIGINT, lambda: exit(0))
signal.signal(signal.SIGTERM, lambda: exit(0))


@click.command()
@click.argument('symbol', nargs=1, required=True)
@click.option('--exchange', required=True,
              help="an exchange such as bitstamp|bitmex")
def main(symbol: str, exchange: str):
    emitter_class_name = pascalcase(exchange) + 'Emitter'
    emitter_class = getattr(exchange_data.emitters.__init__, emitter_class_name)
    emitter = emitter_class(symbol)
    emitter.start()


if __name__ == '__main__':
    main()
