long-orderbook-a3c-v0:
    checkpoint_at_end: True
    checkpoint_freq: 1
    max_failures: 10000
    env: long-orderbook-trading-v0
    run: A3C
    config:
        log_level: DEBUG
        num_workers: 3
        num_envs_per_worker: 5
        num_gpus_per_worker: 0.233
        remote_worker_envs: False
        clip_rewards: False
        sample_batch_size: 24
        train_batch_size: 1000
        batch_mode: complete_episodes
        use_pytorch: false
        vf_loss_coeff: 0.5
        entropy_coeff: 0.01
        gamma: 0.99
        grad_clip: 40.0
        lambda: 1.0
        lr: 0.01
        num_gpus: 0.3
        min_iter_time_s: 60

        model:
            custom_model: deep_lob
            lstm_cell_size: 64
            lstm_use_prev_action_reward: False
            max_seq_len: 24
