long-orderbook-apex-v3:
    checkpoint_at_end: True
    checkpoint_freq: 1
    max_failures: 10000
    env: long-orderbook-trading-v0
    run: APEX
    config:
        clip_rewards: False
        adam_epsilon: .00000001
        beta_annealing_fraction: 1.0
        buffer_size: 100000
        double_q: False
        dueling: False
        exploration_final_eps: 0.01
        exploration_fraction: 0.1
        final_prioritized_replay_beta: 1.0
        hiddens: [512]
        learning_starts: 100000
        lr: .001
        n_step: 3
        noisy: false
        num_atoms: 1
        num_gpus: 1
        prioritized_replay_alpha: 0.5
        schedule_max_timesteps: 2000000

        # APEX
        num_workers: 10
        num_envs_per_worker: 12
        sample_batch_size: 100
        train_batch_size: 1000
        target_network_update_freq: 100000
        timesteps_per_iteration: 200000
