orderbook-apex-v1:
    checkpoint_at_end: True
    checkpoint_freq: 10
    max_failures: 10000
    env: orderbook-trading-v0
    run: APEX
    config:
        adam_epsilon: .00015
        beta_annealing_fraction: 1.0
        buffer_size: 1000000
        double_q: false
        dueling: false
        exploration_final_eps: 0.01
        exploration_fraction: .1
        final_prioritized_replay_beta: 1.0
        hiddens: [1024]
        learning_starts: 10000
        lr: .0001
        n_step: 3
        noisy: false
        num_atoms: 1
        num_gpus: 1
        prioritized_replay_alpha: 0.5
        schedule_max_timesteps: 2000000

        # APEX
        num_workers: 4
        num_envs_per_worker: 5
        sample_batch_size: 48
        train_batch_size: 512
        target_network_update_freq: 10000
        timesteps_per_iteration: 5000
