version: '3.8'

networks:
  public:
    name: public
    external: true

services:
  telegraf:
    image: telegraf:1.17.2-alpine
    volumes:
      - ./telegraf/etc/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    depends_on:
      - influxdb
    links:
      - influxdb
    ports:
      - '0.0.0.0:8125:8125/udp'
    networks:
      - public

  grafana:
    image: grafana/grafana:7.4.2
    user: "472"
    depends_on:
      - influxdb
    env_file: configuration.env
    links:
      - influxdb
    ports:
      - '0.0.0.0:3001:3000'
    volumes:
      - ${HOME}/data/grafana:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
      - ./grafana/dashboards/:/var/lib/grafana/dashboards/
    networks:
      - public

