version: '3.8'

services:
  telegraf:
    image: telegraf:1.17.2-alpine
    volumes:
      - ./telegraf/etc/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    depends_on:
      - influxdb
    links:
      - influxdb
    ports:
      - '0.0.0.0:8125:8125/udp'

  influxdb:
    image: influxdb:1.8.4-alpine
    env_file: configuration.env
    ports:
      - '0.0.0.0:8086:8086'
    volumes:
      - ./:/imports
      - ${HOME}/data/metrics:/var/lib/influxdb

  grafana:
    image: grafana/grafana:7.4.2
    user: "472"
    depends_on:
      - influxdb
    env_file: configuration.env
    links:
      - influxdb
    ports:
      - '0.0.0.0:3000:3000'
    volumes:
      - ${HOME}/data/grafana:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
      - ./grafana/dashboards/:/var/lib/grafana/dashboards/
